// Package openapi implements FR-MCP-06's `vegaload new --from-openapi`
// and the generate_from_spec MCP tool: turning an OpenAPI document into
// a ready-to-run starting point for load testing its endpoints.
//
// It parses JSON OpenAPI specs only — no YAML parser, deliberately, to
// avoid adding a new go.mod dependency (see go.mod's pinning history).
// Most tooling (Swagger UI, most API gateways) can export a spec as
// JSON even when the canonical source is YAML, so this is a real
// limitation but rarely a blocking one.
//
// It also scaffolds a runbook, not a working scenario script. The
// scripting runtimes (internal/scripting/js and /python) can make real
// HTTP/WebSocket calls per FR-CLI-08, but only along a flow someone
// actually wrote — chaining a response from one endpoint into the next
// call, retrying, reading a WebSocket until some condition. An OpenAPI
// spec describes each endpoint in isolation; it says nothing about how
// they relate, so generating a scenario that "chains" them would be
// guessing at an order and a data flow the spec never specified.
// RenderRunbook instead produces the exact `vegaload run -target ...
// -protocol http1 ...` command for each discovered endpoint — a human
// (or an agent) copies the one they want and runs it directly, or uses
// the runbook as a checklist of calls to wire into a hand-written
// FR-CLI-08 scenario themselves.
package openapi

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// Endpoint is one operation an OpenAPI document declares: an HTTP
// method on a path, with its summary (when the spec provides one) for
// a human-readable runbook entry.
type Endpoint struct {
	Method  string
	Path    string
	Summary string
}

// Spec is the minimal slice of an OpenAPI document this package needs:
// a title for the generated runbook's heading, a base URL to combine
// with each endpoint's path, and the endpoints themselves.
type Spec struct {
	Title     string
	BaseURL   string
	Endpoints []Endpoint
}

// httpMethods lists the operation keys OpenAPI defines under a path
// item, in the fixed order a runbook should present them — not
// alphabetical, but the order a human thinks about a resource's verbs
// (read before write, write before delete).
var httpMethods = []string{"get", "post", "put", "patch", "delete", "head", "options"}

// rawDocument mirrors just the fields of an OpenAPI 3.x JSON document
// that Parse needs; everything else in a real spec (components,
// security schemes, examples) is ignored.
type rawDocument struct {
	Info struct {
		Title string `json:"title"`
	} `json:"info"`
	Servers []struct {
		URL string `json:"url"`
	} `json:"servers"`
	Paths map[string]map[string]struct {
		Summary string `json:"summary"`
	} `json:"paths"`
}

// Parse reads an OpenAPI 3.x document from data (JSON only — see this
// package's doc comment) and returns the Spec RenderRunbook needs.
func Parse(data []byte) (*Spec, error) {
	var doc rawDocument
	if err := json.Unmarshal(data, &doc); err != nil {
		return nil, fmt.Errorf("openapi: not valid JSON (only JSON OpenAPI specs are supported, not YAML): %w", err)
	}
	if len(doc.Paths) == 0 {
		return nil, fmt.Errorf("openapi: no paths found in the spec")
	}

	spec := &Spec{Title: doc.Info.Title}
	if len(doc.Servers) > 0 {
		spec.BaseURL = strings.TrimSuffix(doc.Servers[0].URL, "/")
	}
	if spec.Title == "" {
		spec.Title = "API"
	}

	paths := make([]string, 0, len(doc.Paths))
	for p := range doc.Paths {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	for _, p := range paths {
		ops := doc.Paths[p]
		for _, method := range httpMethods {
			op, ok := ops[method]
			if !ok {
				continue
			}
			spec.Endpoints = append(spec.Endpoints, Endpoint{
				Method:  strings.ToUpper(method),
				Path:    p,
				Summary: op.Summary,
			})
		}
	}

	if len(spec.Endpoints) == 0 {
		return nil, fmt.Errorf("openapi: no operations found under any path (only get/post/put/patch/delete/head/options are recognized)")
	}
	return spec, nil
}

// RenderRunbook renders a Markdown document: one `vegaload run` command
// per endpoint, ready to copy and run (or for an MCP-driven agent to
// pass straight to the run_test tool's target/protocol/executor
// arguments). name is used only in the heading, to connect the runbook
// back to the scaffold command that produced it.
func (s *Spec) RenderRunbook(name string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s — load test runbook\n\n", s.Title)
	fmt.Fprintf(&b, "Generated by `vegaload new %s -from-openapi <spec>`.\n\n", name)
	b.WriteString("This is a runbook, not a runnable scenario: an OpenAPI spec describes each " +
		"endpoint on its own, not how their responses should feed into each other, so each entry " +
		"below is the exact protocol-direct command for one endpoint this spec declares. Copy the " +
		"one you want, adjust -vus/-duration/-executor, and run it directly — or use these as a " +
		"checklist of calls to wire into a hand-written scenario (see AGENTS.md) if you want them " +
		"chained together.\n\n")

	for _, ep := range s.Endpoints {
		target := s.BaseURL + ep.Path
		if ep.Summary != "" {
			fmt.Fprintf(&b, "## %s %s — %s\n\n", ep.Method, ep.Path, ep.Summary)
		} else {
			fmt.Fprintf(&b, "## %s %s\n\n", ep.Method, ep.Path)
		}
		fmt.Fprintf(&b, "```\nvegaload run -target %q -protocol http1 -method %s -vus 10 -duration 30s\n```\n\n",
			target, ep.Method)
	}
	return b.String()
}
